spring:
  profiles:
    active: dev,prod
resilience4j:
  retry:
    instances:
      hubspotApi:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.web.client.HttpClientErrorException.TooManyRequests